# Generated by Django 2.0.2 on 2018-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
