# Generated by Django 2.0.3 on 2018-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=300, unique_for_date='created')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
