# Generated by Django 2.0.3 on 2018-05-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20180512_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myitem',
            name='slug',
        ),
    ]
